### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [CestDiego/sweetgreen.el#3]
Please add a free license for this project.

**Comment by CestDiego** [comment]
https://github.com/CestDiego/sweetgreen.el/blob/master/sweetgreen.el#L27-L40 Is this not enough?

**Comment by pizzamaker** [comment]
Ah thanks! It should be enough. To avoid annoiances like this you could also create a LICENSE.md file with the contents of your licence. But that's optional.
